[project]
name = "clamav-gui"
version = "0.0.11"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "darkdetect>=0.8.0",
    "psutil>=7.0.0",
    "pyinstaller>=6.12.0",
    "ttkthemes>=3.2.2",
    "wmi>=1.5.1",
]
